---
abstract: 'parses local .pm files as PAUSE does'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  File::Path: 0
  Test::More: 0.47
  Test::UseAllModules: 0.10
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.76, CPAN::Meta::Converter version 2.132620'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Parse-LocalDistribution
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 0
  Parse::CPAN::Meta: 0
  Parse::PMFile: 0.09
resources:
  repository: https://github.com/charsbar/Parse-LocalDistribution
version: 0.05
